version: '3.9'

services:
  symfony-nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
     - ./../symfony:/var/www/html
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./logs/nginx:/var/log/nginx:cached
     - ./symfony:/var/www/symfony:cached
    external_links:
     - symfony-mariadb:symfony-mariadb
     - symfony-php:symfony-php
  symfony-mariadb:
    image: mariadb
    container_name: symfony-mariadb
    restart: always
    ports:
        - "${MYSQL_PORT}:3306"
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  symfony-php:
    container_name: symfony-php
    image: php:8.0-fpm-alpine
    ports:
      - "8081:80"
    volumes:
      - ../symfony/:/var/www/html
    restart: always
    environment:
     - "PMA_HOST=mariadb"
     - "PMA_PORT=3306"
    external_links:
     - symfony-mariadb:symfony-mariadb